[package]
name = "vibelive"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = "0.20.1"
num = "0.4.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"